In [270]:
import numpy as np
np.set_printoptions(precision=5, suppress=True)

# Создание и заполнение матрицы

Создаем и заполняем матрицу входными данными из файла __data.txt__. Размерность определяется автоматически.
Предполагается, что данные введены корректно в естественной форме:
$$\begin{bmatrix}
    a_{11} & a_{12} & ... & a_{1n} \\
    a_{21} & a_{22} & ... & a_{2n}\\
    . & . & ... & .\\
    . & . & ... & .\\
    a_{n1} & a_{n2} & ... & a_{nn}
  \end{bmatrix}
 \begin{bmatrix}
    b_1\\
    b_2\\
    .\\
    .\\
    b_n
  \end{bmatrix}$$

In [237]:
data = np.loadtxt("data2.txt", delimiter=' ', dtype=np.float)
data_cpy = np.copy(data)
n = data.shape[0] # размерность
print(data) # для наглядности выведем матрицу

[[ 2.  3. 11.  5.  2.]
 [ 1.  1.  5.  2.  1.]
 [ 2.  1.  3.  2. -3.]
 [ 1.  1.  3.  4. -3.]]


# Реализация модифицированного метода Гаусса

In [238]:
def Gauss(data, n):
    # Прямой ход
    permutations = np.array(range(0, n))
    for i in range(0, n):
        if data[i][i] == 0: # i-й элемент строки нулевой?
            for j in range(i + 1, n):
                if data[j][i] != 0:
                    data[[i, j]] = data[[j, i]] # меняем местами строчки
                    break
        ### Модифицированный метод гаусса (с выбором главного элемента)
        col_max = i + np.argmax(abs(data[i][i:n]))
        data[:,[i, col_max]] = data[:,[col_max, i]]
        permutations[i], permutations[col_max] = permutations[col_max], permutations[i]
        ###
        data[i] /= data[i][i] # делим i-ю строку на её i-й элемент
        for j in range(i + 1, n):
            data[j] -= data[i] * data[j][i] # вычитаем из всех остальных строк i-ю, умноженную на нужное число
    # Обратный ход
    x = data[:, n] # создаем вектор неизвестных, заранее присвоив ему значение столбца свободных членов
    for i in range(n - 1, -1, -1): # последовательно восставливаем ответ
        for j in range(n - 1, i, -1):
            x[i] -= x[j] * data[i][j]
    res = np.array(list(zip(x, permutations))) # массив пар (x, i), где x является i-й компонентой решения системы
    res = res[res[:, 1].argsort()] # сортировка по номеру переменной
    x = res[:, 0] # вытаскиваем вектор решений в естественном порядке (от x_0 до x_n)
    return x # возвращаем решение системы

In [239]:
print(Gauss(data, n))

[-2. -0.  1. -1.]


Сверим найденное решение с решением, полученным с использованием специальной библиотеки Python для решения задач линейной алгебры.

In [240]:
print(np.linalg.solve(data_cpy[:, :n], data_cpy[:, n]))

[-2. -0.  1. -1.]


Как видим, решение полностью совпало.

# Вычисление определителя и обратной матрицы

Для вычисления обратной матрицы присоединим к исходной справа единичную матрицу и будем приводить исходную к единичной, выполняя все преобразования на присоединенной. В итоге присоединенная матрица окажется обратной к исходной. Параллельно вычисляем определитель, перемножая получаемые по ходу преобразований элементы на главной диагонали (предполагается, что определитель ненулевой).

In [241]:
def det_inverse(data_cpy, n):
    det = 1
    data_inv = data_cpy[:, :n]
    id = np.identity(n) # единичная матрица порядка n
    for i in range(0, n): # присоединяем
        data_inv = np.column_stack((data_inv, id[:, i]))
    for i in range(0, n): # приводим "левую" матрицу к нижнитреугольному виду с единицами на диагонали
        if data_inv[i][i] == 0: # i-й элемент строки нулевой?
            for j in range(i + 1, n):
                if data_inv[j][i] != 0:
                    data_inv[[i, j]] = data_inv[[j, i]] # меняем местами строчки
                    break
        det *= data_inv[i][i] # последовательно вычисляем определитель
        data_inv[i] /= data_inv[i][i] # делим i-ю строку на её i-й элемент
        for j in range(i + 1, n):
            data_inv[j] -= data_inv[i] * data_inv[j][i] # вычитаем из всех остальных строк i-ю, умноженную на нужное число
    for i in range(n - 1, -1, -1): # # приводим "левую" матрицу к единичному виду
        for j in range(i - 1, -1, -1):
            data_inv[j] -= data_inv[i] * data_inv[j][i] # вычитаем из всех остальных строк i-ю, умноженную на нужное число
    inverse_matrix = data_inv[:, n:] # вытаскиваем нужную часть
    return det, inverse_matrix

In [242]:
det, inverse_matrix = det_inverse(data_cpy, n)
print(det) # выводим определитель
print(inverse_matrix) # выводим обратную матрицу

14.0
[[-0.28571  0.28571  0.71429 -0.14286]
 [ 1.28571 -2.78571  0.28571 -0.35714]
 [-0.14286  0.64286 -0.14286 -0.07143]
 [-0.14286  0.14286 -0.14286  0.42857]]


Проверим полученные результаты, опять же, с помощью библиотечных функций.

In [243]:
print(np.linalg.det(data_cpy[:, :n])) # определитель
print(np.dot(data_cpy[:, :n], inverse_matrix)) # умножаем исходную матрицу на полученную обратную

14.000000000000004
[[ 1. -0. -0.  0.]
 [ 0.  1. -0. -0.]
 [ 0.  0.  1. -0.]
 [ 0.  0. -0.  1.]]


# Тестирование

Далее будут представлены резульаты тестирование программы на системах линейных алгебраических уравнений, которые были предложены в приложении 1-2. Первая из систем была проверена выше. Ниже приводятся непосредственные ответы, полученные с помощью описанной выше программы, а также с помощью функции __np.linalg.solve__.

In [284]:
# Вторая матрица
data2 = np.loadtxt("data3.txt", delimiter=' ', dtype=np.float)
data2 = data2[:, :data2.shape[0]]
print("%.5f" % np.linalg.det(data2))
print(data2)

-0.00000
[[ 2. -1.  1.  2.]
 [ 6. -3.  2.  4.]
 [ 6. -3.  4.  8.]
 [ 4. -2.  1.  1.]]


Вторая матрица из приложения 1-2 является вырожденной, поэтому рассмотренные выше методы для неё не годятся.

In [293]:
# Третья матрица
data3 = np.loadtxt("data4.txt", delimiter=' ', dtype=np.float)
data3_cpy = np.copy(data3)
data3_cpy2 = np.copy(data3)
n = data3.shape[0]
print(Gauss(data3, n))
print(np.linalg.solve(data3_cpy[:, :n], data3_cpy[:, n]))

res = det_inverse(data3_cpy2[:, :n], n)
print(res[0])
print(res[1])
res2 = np.linalg.det(data3_cpy[:, :n]), np.linalg.inv(data3_cpy[:, :n])
print(res2[0])
print(res2[1])

[ 0.91667  1.11111  0.97222 -0.11111]
[ 0.91667  1.11111  0.97222 -0.11111]
36.0
[[-0.58333  0.91667 -0.16667 -0.08333]
 [ 0.77778 -0.88889  0.88889  0.11111]
 [-0.19444 -0.02778  0.27778 -0.02778]
 [ 0.22222 -0.11111  0.11111 -0.11111]]
36.0
[[-0.58333  0.91667 -0.16667 -0.08333]
 [ 0.77778 -0.88889  0.88889  0.11111]
 [-0.19444 -0.02778  0.27778 -0.02778]
 [ 0.22222 -0.11111  0.11111 -0.11111]]


Как видим, всё совпадает.

Теперь протестируем алгоритмы на следующей системе (приложение 2, пример 1, вариант 6). Коэффициенты матрицы определяются как: $$\begin{equation*}
a_{ij} = 
 \begin{cases}
   \frac{i + j}{m + n} , i \neq j,\\
   n + m^2 + \frac{j}{m} + \frac{i}{n} , i = j,\\
 \end{cases}
\end{equation*}$$
где $i, j \in \{1,...,n\}$, $n = 25$, $m=10$.<br>Столбец свободных членов определяется как $$b_i = i^2 - n$$

In [311]:
n = 25
m = 10
data = np.empty((n, n + 1))
for i in range(0, n):
    for j in range(0, n):
        if i == j:
            data[i][j] = n + m*m + (j + 1) / m + (i + 1) / n
        else:
            data[i][j] = (i + j + 2) / (m + n)
for i in range(0, n):
    data[i][n] = (i + 1) * (i + 1) - n
data_cpy = np.copy(data)
data_cpy2 = np.copy(data)
n = data.shape[0]
print(Gauss(data, n)) # реализованное решение
print(np.linalg.solve(data_cpy[:, :n], data_cpy[:, n])) # библиотечное решение

res1 = det_inverse(data_cpy2[:, :n], n)
res2 = np.linalg.det(data_cpy[:, :n]), np.linalg.inv(data_cpy[:, :n])
print("Det: ", res1[0], res2[0]) # определители
print(res1[1] - res2[1]) # разность

[-0.35441 -0.33761 -0.30487 -0.25622 -0.19168 -0.11129 -0.01509  0.09691
  0.22467  0.36815  0.52732  0.70216  0.89264  1.09872  1.32036  1.55755
  1.81026  2.07844  2.36207  2.66112  2.97556  3.30536  3.65049  4.01091
  4.38661]
[-0.35441 -0.33761 -0.30487 -0.25622 -0.19168 -0.11129 -0.01509  0.09691
  0.22467  0.36815  0.52732  0.70216  0.89264  1.09872  1.32036  1.55755
  1.81026  2.07844  2.36207  2.66112  2.97556  3.30536  3.65049  4.01091
  4.38661]
Det:  3.7556660492642055e+52 3.755666049264226e+52
[[ 0.  0. -0. -0. -0.  0.  0.  0. -0. -0.  0.  0.  0.  0.  0. -0. -0.  0.
   0. -0.  0. -0.  0.  0. -0.]
 [-0. -0. -0.  0. -0.  0.  0.  0. -0.  0. -0. -0.  0.  0. -0.  0. -0.  0.
   0.  0.  0. -0.  0. -0. -0.]
 [-0. -0.  0. -0.  0.  0.  0.  0. -0. -0. -0. -0.  0.  0.  0.  0. -0.  0.
  -0. -0.  0.  0. -0. -0. -0.]
 [ 0.  0.  0.  0.  0. -0.  0.  0. -0.  0.  0. -0.  0.  0. -0. -0. -0.  0.
   0.  0.  0. -0. -0.  0. -0.]
 [ 0. -0. -0. -0.  0.  0.  0.  0. -0.  0. -0. -0. -0.  0.  0. -0. -0.

Программа снова успешно прошла все тесты.

# Определение числа обусловленности

Определим число обусловленности $||A||\times||A^{-1}||$ матрицы коэффициентов $A$. Для этого вычислим норму матрицы $A$ (и матрицы, обратной к ней) по формуле $$||A|| = \max\limits_{1\leq i\leq n} \sum_{j=1}^n |a_{ij}|$$ 

In [312]:
def mat_norm(data, n):
    max = 0
    for i in range(0, n):
        max_i = 0
        for j in range(0, n):
            max_i += abs(data[i][j])
        if max_i > max:
            max = max_i
    return max

Найдем, к примеру, число обусловленностей для матрицы коэффициентов одной из рассмотренный выше систем.

In [325]:
data3 = np.loadtxt("data4.txt", delimiter=' ', dtype=np.float)
print(data3)
data3_cpy = np.copy(data3_cpy)
n = data3.shape[0]
_, inv = det_inverse(data3[:, :n], n)
print(mat_norm(data3_cpy, n) * mat_norm(inv, n))

[[ 1.  1. -3.  1. -1.]
 [ 2.  1. -2.  0.  1.]
 [ 1.  1.  1.  0.  3.]
 [ 1.  2. -3. -7.  1.]]
34.666666666666664


Метод Гаусса для плохо обусловленных матриц коэффициентов является вычислительно неустойчивым. Уменьшить вычислительную ошибку можно с помощью модифицированного метода Гаусса с выделением главного элемента, который является условно устойчивым. Широкое применение метода Гаусса связано с тем, что плохо обусловленные матрицы встречаются на практике относительно редко.